In [2]:
# Step 1: Data Preparation
data = pd.read_csv('simulated_predictive_maintenance_data.csv')

In [3]:
data.head()

Temperature   Pressure  Vibration   Timestamp  FailureLabel
0    74.967142  68.617357  76.476885  2023-01-01             0
1    85.230299  67.658466  67.658630  2023-01-02             1
2    85.792128  77.674347  65.305256  2023-01-03             1
3    75.425600  65.365823  65.342702  2023-01-04             0
4    72.419623  50.867198  52.750822  2023-01-05             0

In [4]:
# Preprocessing
scaler = MinMaxScaler()
data[['Temperature', 'Pressure', 'Vibration']] = scaler.fit_transform(data[['Temperature', 'Pressure', 'Vibration']])

In [5]:
data

Temperature  Pressure  Vibration   Timestamp  FailureLabel
0       0.623065  0.490970   0.504820  2023-01-01             0
1       0.851555  0.475798   0.368577  2023-01-02             1
2       0.864063  0.634273   0.332218  2023-01-03             1
3       0.633272  0.439523   0.332796  2023-01-04             0
4       0.566349  0.210120   0.138251  2023-01-05             0
..           ...       ...        ...         ...           ...
176     0.570303  0.369762   0.503414  2023-06-26             0
177     0.142574  0.502391   0.217649  2023-06-27             0
178     0.367361  0.520346   0.271817  2023-06-28             0
179     0.426866  0.672067   0.315622  2023-06-29             1
180     0.698532  0.334100   0.486607  2023-06-30             0

[181 rows x 5 columns]

In [6]:
timestamp=10
i=1

In [7]:
len(data)

181

In [8]:
len(data) - timestamp - 1

170

In [9]:
sequence = data[['Temperature', 'Pressure', 'Vibration']].iloc[i:(i + timestamp)].values
sequence

array([[0.8515552 , 0.47579802, 0.36857733],
       [0.86406331, 0.63427343, 0.33221761],
       [0.63327158, 0.43952287, 0.33279616],
       [0.566349  , 0.21011961, 0.13825114],
       [0.38729753, 0.3525924 , 0.4533029 ],
       [0.31032563, 0.2893862 , 0.63119485],
       [0.46221558, 0.52353133, 0.18462746],
       [0.3912837 , 0.53039737, 0.22692265],
       [0.59612281, 0.41781119, 0.35968479],
       [0.37852159, 0.80592186, 0.40266625]])

In [10]:
# Step 2: Sequence Generation
datax = []
datay = []
timestamp = 10  # Define sequence length

for i in range(len(data) - timestamp - 1):
    sequence = data[['Temperature', 'Pressure', 'Vibration']].iloc[i:(i + timestamp)].values
    datax.append(sequence)
    datay.append(data['FailureLabel'].iloc[i + timestamp])

In [11]:
datax

[array([[0.62306483, 0.49096998, 0.50481969],
        [0.8515552 , 0.47579802, 0.36857733],
        [0.86406331, 0.63427343, 0.33221761],
        [0.63327158, 0.43952287, 0.33279616],
        [0.566349  , 0.21011961, 0.13825114],
        [0.38729753, 0.3525924 , 0.4533029 ],
        [0.31032563, 0.2893862 , 0.63119485],
        [0.46221558, 0.52353133, 0.18462746],
        [0.3912837 , 0.53039737, 0.22692265],
        [0.59612281, 0.41781119, 0.35968479]]),
 array([[0.8515552 , 0.47579802, 0.36857733],
        [0.86406331, 0.63427343, 0.33221761],
        [0.63327158, 0.43952287, 0.33279616],
        [0.566349  , 0.21011961, 0.13825114],
        [0.38729753, 0.3525924 , 0.4533029 ],
        [0.31032563, 0.2893862 , 0.63119485],
        [0.46221558, 0.52353133, 0.18462746],
        [0.3912837 , 0.53039737, 0.22692265],
        [0.59612281, 0.41781119, 0.35968479],
        [0.37852159, 0.80592186, 0.40266625]]),
 array([[0.86406331, 0.63427343, 0.33221761],
        [0.63327158, 0.4395228

In [12]:
datay

[1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [13]:
trainx = np.array(datax)
trainy = np.array(datay)

In [14]:
trainx

array([[[0.62306483, 0.49096998, 0.50481969],
        [0.8515552 , 0.47579802, 0.36857733],
        [0.86406331, 0.63427343, 0.33221761],
        ...,
        [0.46221558, 0.52353133, 0.18462746],
        [0.3912837 , 0.53039737, 0.22692265],
        [0.59612281, 0.41781119, 0.35968479]],

       [[0.8515552 , 0.47579802, 0.36857733],
        [0.86406331, 0.63427343, 0.33221761],
        [0.63327158, 0.43952287, 0.33279616],
        ...,
        [0.3912837 , 0.53039737, 0.22692265],
        [0.59612281, 0.41781119, 0.35968479],
        [0.37852159, 0.80592186, 0.40266625]],

       [[0.86406331, 0.63427343, 0.33221761],
        [0.63327158, 0.43952287, 0.33279616],
        [0.566349  , 0.21011961, 0.13825114],
        ...,
        [0.59612281, 0.41781119, 0.35968479],
        [0.37852159, 0.80592186, 0.40266625],
        [0.27700059, 0.6429932 , 0.21613079]],

       ...,

       [[0.93757713, 0.29155958, 0.49173053],
        [0.3676269 , 0.43577174, 0.3132265 ],
        [0.32012883, 0

In [15]:
trainy

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [16]:
# Step 3: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(trainx, trainy, test_size=0.2, random_state=42)

In [19]:
# Step 6: Evaluate the Model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy}")


2/2 [==============================] - 0s 4ms/step - loss: 0.6539 - accuracy: 0.6471
Test Accuracy: 0.6470588445663452
